# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ae6a722bf28d5d338582fbdaa937f18610afd34080fa9b61992d7879c7ec0f4039b53de2ce5a7c571f151722803dfef405275bc31e2efb27e91cc5111297ac1

test:
  secret_key_base: 247b69296ad5b4e6e90abaf0d02e556e6785f1b8e49a50af19423c1289a3c0abbd5ba1593e9fee2ed86a10a7e0eaf56f9f33857728fdc351efc3d69341ca2f32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
